version: '3.0'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.14.3"
    ports:
      - "9200:9200"
    environment:
      - ELASTIC_PASSWORD=admin
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=basic
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
  kibana:
    image: "docker.elastic.co/kibana/kibana:8.14.3"
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.license.self_generated.type=basic
volumes:
  elasticsearch_data: